env:
  - DOCKER_USERNAME=fengzhanyuan
sudo: required
language: go
services:
  - docker
go:
  - "1.10.x"
before_install:
  - docker info
  - docker ps -a
  - go get -u -v github.com/kardianos/govendor
install:
  - govendor sync
  - pwd
  - ls ./vendor
script:
  - go build -o skyline
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker version
  - pwd
  - docker build -t lyrewing/skyline-api:1.0 .
  - docker push lyrewing/skyline-api:1.0
