env:
  - DOCKER_USERNAME=fengzhanyuan
sudo: required
language: go
services:
  - docker
go:
  - "1.10.x"
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - go get -u -v github.com/kardianos/govendor
install:
  - cp -rf ./ $GOPATH/src/skyline-api
  - cd $GOPATH/src/skyline-api
  - govendor sync
  - pwd
  - ls
script:
  - go build -o skyline
  - ls
  - docker build -t lyrewing/skyline-api:1.0.1 .
  - docker push lyrewing/skyline-api:1.0.1
